<a href="https://colab.research.google.com/github/alon3god/DS_intro/blob/homework/n2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# №1


In [ ]:

b = np.arange(31)
print("b:\n", b)
mask = b % 3 == 0
print("Кратные 3:", b[mask])


b:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Кратные 3: [ 0  3  6  9 12 15 18 21 24 27 30]


# №2

In [ ]:

M = np.arange(30)
print(M)
m = M.reshape(5,6)
print(m)
print("Сумма по столбцам:", m.sum(axis=0))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Сумма по столбцам: [60 65 70 75 80 85]
